### ISSUE TITLE
New work based on your work

### ISSUE THREAD

**Issue by tammoterhark** [mofog/BootstrapForLimeSurvey#15]
Hi mofog, we wanted to design and build a better LimeSurvey template and while investigating this, we found your work. We based several of our solutions on your work, thank you for making your work public.

You can find our work at: https://github.com/toolsforresearch/tfr-responsive

**Comment by mofog** [comment]
Hey tammoterhark,

Thank you very much for your message and the credits – they really made my day! Your template surely looks nice, and I think our work may actually help to provide users a better LimeSurvey experience.

Well, I don't want to sound demanding or so, but do you think it would be possible that I get a free premium licence :)? That would be absolutely terrific!

**Comment by tammoterhark** [comment]
Hi mofog, would it be possible to have a short Skype conversation about
what you encountered during development. We have some questions....

We are in The Netherlands, Europe. Please email me:
tammo.terhark@toolsforresearch.com
Tammo
