### ISSUE TITLE
problems with conditional questions

### ISSUE THREAD

**Issue by pgee70** [mofog/BootstrapForLimeSurvey#16]
Hi
Using LS 2.05+, i found that conditional questions were not working.  This took me a few hours for me to fix because of the way that LS combines, and injects code into the template files.  I wanted to share this with you by way of thanks for the excellent work you did on this template.

To the start of template.js I added

setJsVar(); // this is needed to turn LS-injected parameters in the <head> into variables for use in javascript.

The order of operations in the startpage.pstpl is also important, this startpage.pstpl (before the </head> tag worked for me: as LS prepends the <title> tag with its own stuff

startpage.pstpl:

	<meta name="generator" content="LimeSurvey http://www.limesurvey.org" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0 user-scalable=no"/>
	{TEMPLATECSS}
	<link rel="shortcut icon" href="{TEMPLATEURL}images/favicon.ico" />
	{GOOGLE_ANALYTICS_JAVASCRIPT}
	<title>{SURVEYNAME} {GROUPNAME}</title>
	<link rel="stylesheet" type="text/css" href="{TEMPLATEURL}bootstrap/css/bootstrap.min.css"/>
	<link rel="stylesheet" type="text/css" href="{TEMPLATEURL}bootstrap/css/jquery-ui-bootstrap/jquery-ui.css"/>
	<link rel="stylesheet" type="text/css" href="{TEMPLATEURL}bootstrap/css/jquery-ui-bootstrap/jquery-ui.ie.css"/>
	<link rel="stylesheet" type="text/css" href="{TEMPLATEURL}bootstrap/css/bootstrap-theme.min.css"/>
	<link rel="stylesheet" type="text/css" href="{TEMPLATEURL}css/template.css"/>
	<script type="text/javascript" src="{TEMPLATEURL}bootstrap/js/bootstrap.min.js"></script>
	{TEMPLATEJS}
</head>

**Comment by mofog** [comment]
Hi pgee70,

Thank your very much for your contribution. Could you also create a pull request for that :) ?
