### ISSUE TITLE
drag and drop question elements

### ISSUE THREAD

**Issue by pgee70** [mofog/BootstrapForLimeSurvey#17]
drag and drop question rankings are broken --
![image](https://cloud.githubusercontent.com/assets/5938974/9535881/66e519f2-4d69-11e5-9829-dbc02a5d358d.png)

this can be fixed by editing template.js::setupAnswers() from:

		bfls('.answer .answer ul').each(function(index) {
			if (bfls('.answer .answer ul').eq(index).children('li').length < 13) {
				columnWidth = Math.floor(12/bfls('.answer .answer ul').eq(index).children('li').length);
			} else {
				columnWidth = 12;		
			}
				
			bfls('.answer .answer ul').eq(index).children().wrapAll('<div class="row"></div>');
			bfls('.answer .answer ul').eq(index).children('div').children('li').wrap('<div class="col-md-'+ columnWidth +'"></div>');
		});
to 

		bfls('.answer .answer ul').each(function(index) {
			if (bfls(this).closest('.ranking-answers').length == 0)
			{
				if (bfls('.answer .answer ul').eq(index).children('li').length < 13) {
					columnWidth = Math.floor(12/bfls('.answer .answer ul').eq(index).children('li').length);
				} else {
					columnWidth = 12;		
				}
				
				bfls('.answer .answer ul').eq(index).children().wrapAll('<div class="row"></div>');
				bfls('.answer .answer ul').eq(index).children('div').children('li').wrap('<div class="col-md-'+ columnWidth +'"></div>');		
			}
		});

to give:

![image](https://cloud.githubusercontent.com/assets/5938974/9535922/cdee8c64-4d69-11e5-8e97-cadd0533c981.png)

**Comment by mofog** [comment]
Thank you very much. Currently, I do not have a running LS installation at hand, so I just included your fix :-)
