### ISSUE TITLE
How I use it?

### ISSUE THREAD

**Issue by rinodung** [mofog/BootstrapForLimeSurvey#18]
I download and place it in template folder but in admin page i can not see it to set it as new template?
![lime-template-error](https://cloud.githubusercontent.com/assets/7805715/9829755/33351d98-593d-11e5-82fe-ccedb912b904.png)

**Comment by mofog** [comment]
Hi rinodung,

You should click on the "Download ZIP" button and unzip the file. That should give you a directory called "BootstrapForLimeSurvey-master". Rename that to "BootstrapForLimeSurvey" and put it in "upload/templates"; that should work.
