### ISSUE TITLE
Use on a phone / array questions

### ISSUE THREAD

**Issue by DieterKoblenz** [mofog/BootstrapForLimeSurvey#19]
On a phone (HTC One) using an array makes it impossible to answer questions even in landscape mode. The sentence does not break and the answers aren't even visible.

Are there any workarounds for this behaviour?

Example: http://postimg.org/image/yjc6hufud/

**Comment by mofog** [comment]
Hey there,
It seems that this is the intended behavior of Bootstrap. I tried to reproduce your setup and was able to scroll horizontally. If your that's not possible on your phone–or if you really want to change the visual appearance–you may add this code to the end of the "template.css" file:

    @media screen and (max-width: 767px) {
        .table-responsive>.table>tbody>tr>td, .table-responsive>.table>tbody>tr>th, .table-responsive>.table>tfoot>tr>td, .table-responsive>.table>tfoot>tr>th, .table-responsive>.table>thead>tr>td, .table-responsive>.table>thead>tr>th {
            white-space: normal !important;
        }
    }

I hope that helps.

**Comment by rest1014** [comment]
Hey,

I've realized the same problem and tried this as well. But nothing changes. 
I found this page: http://bootsnipp.com/snippets/featured/no-more-tables-respsonsive-table. Check the first comment. Do I have to copy this into template.js? Best regards Steffen

// Dynamically add the data-title attributes:
$(document).ready(function () {
$(".nmt").each(function() {
var nmtTable = $(this);
var nmtHeadRow = nmtTable.find("thead tr");
nmtTable.find("tbody tr").each(function () {
var curRow = $(this);
for (var i = 0; i < curRow.find("td").length; i++) {
var rowSelector = "td:eq(" + i + ")";
var headSelector = "th:eq(" + i + ")";
curRow.find(rowSelector).attr('data-title', nmtHeadRow.find(headSelector).html());
}
});

});
});

**Comment by mofog** [comment]
Hey Steffen,
I verified the fix proposed in my previous comment. However–if you like–you could add your JavaScript code inbetween lines 63 and 64 of template.js. But then, you would also have to make sure that all corresponding tables get the additional "nmt" class. So, in short, just adding your code won't work.
