### ISSUE TITLE
multiple choice questions on medium screens.

### ISSUE THREAD

**Issue by pgee70** [mofog/BootstrapForLimeSurvey#20]
see images - on medium + screens, the text is hard to read - this is caused by the code that works out the columns - it tries to have a maximum of 12 columns - great for short text - but not so good for longer answers. 
I propose to make the columns set to a maximum of 3, and use the  BS row class properly so that there is not a jaggard wrap where a long answer could cause two short answers to wrap underneath each other.

before:
![before](https://cloud.githubusercontent.com/assets/5938974/10323780/fb229aa0-6cd0-11e5-9f7f-128959b24294.png)
after:
![after](https://cloud.githubusercontent.com/assets/5938974/10323786/0155df54-6cd1-11e5-8d1f-de02232db732.png)

changes to setupAnswers in template.js - note the different coding styling - not using .eq()  using ('tag',this)  -- it reads easier.

    bfls('.answer .tip').addClass('text-muted small');
    bfls('.answer .answer ul').addClass('list-unstyled');
	bfls('.answer .answer ul').each(function(index) {
		if (bfls(this).closest('.ranking-answers').length == 0)
		{
			var lis = bfls('li',this);
			var li_count = bfls('li',this).length;
			if (li_count < 4) {
				columns = Math.floor(12/li_count);
			} else {
				columns = 3;
			}
			var rows = [];
			for (var i = 0 ; i < Math.ceil(li_count / columns) ; i++)
			{
				rows[i]=Array();
				for (var j = 0 ; j < columns; j++)
				{
					rows[i][j] = lis[i * columns + j];
				}
			}
			bfls('li',this).remove();
			for (var i = 0 ; i < rows.length ; i++)
			{
				if (bfls('.row-'+i,this).length == 0)
				{
					bfls(this).append('<div class="row row-' + i + '"></div>');
				}
				for (var j = 0 ; j < rows[i].length ; j ++ )
				{
					bfls('.row-'+i , this).append(rows[i][j]);
				}
			}
			bfls('li',this).wrap('<div class="col-md-'+  Math.floor(12/columns) +'"></div>');
		}
	});

**Comment by mofog** [comment]
Thank you, pgee70! It took quite a while, but today, I included your code in my master branch. Good work!
