### ISSUE TITLE
Previous button not working

### ISSUE THREAD

**Issue by nagim** [mofog/BootstrapForLimeSurvey#21]
Hi,

I tested your template and it's awesome.
But every time I want to go back to the previous page, it does not go back, instead it acts like I pressed the **Next** button (marking mandatory questions not answered, etc.).

Could you please take a look on the issue?

I'm using Version 2.00+

Thanks,
Imre

**Comment by mofog** [comment]
Hello,
Thank you for your feedback! I created a test survey and the previous button as well as the question index seems to work fine. I guess the issue might be related to the structure or the settings of your survey. It could be an issue in your specific LimeSurvey version.

**Comment by nagim** [comment]
Hi,
Thanks for looking into it!
What Limesurvey version have you tested it with?
It shouldn't be settings, I tried that and also tried it with other surveys as well, same behavior.
Meanwhile I confirmed that pressing *Previous* does exactly the same as the *Next* (it submits answers).

**Comment by mofog** [comment]
I'm using Version 2.06+ Build 160129.

**Comment by nagim** [comment]
Since I have no time to do an upgrade and verify all surveys I'm running, I did an ugly hack workaround  (disabled the previous button portion in the `fixui()` function of the template.js and fixed the display), now it works fine. Also the glyphicons in the modals were not showing, so I replaced those as well.

**Comment by mofog** [comment]
Perfect, whatever suits you :)
