### ISSUE TITLE
limesurvey.org extension / template

### ISSUE THREAD

**Issue by Shnoulle** [mofog/BootstrapForLimeSurvey#23]
Hi @mofog,

I don't see your template in https://www.limesurvey.org/index.php?option=com_sobipro&sid=55:Templates&Itemid=729 .
It take some minute to put the link to http://mofog.github.io/BootstrapForLimeSurvey/ . Maybe you can do it :) .

I think your template is great and a lot of LS user can want it :)

**Comment by mofog** [comment]
Hi there,

Thank you very much, I appreciate it! I tried to add it to the list some time ago, but it didn't work. I think I also filed a bug report about this issue somewhere, but nothing ever happened :) So maybe you could give it a try?

**Comment by c-schmitz** [comment]
It is approved, now.

**Comment by Shnoulle** [comment]
Thank you @c-schmitz ;)

**Comment by mofog** [comment]
Thank you, guys!
