### ISSUE TITLE
Need a little assist getting started

### ISSUE THREAD

**Issue by twbo1a** [mofog/BootstrapForLimeSurvey#24]
Hi, thanks for creating this. I extracted the zip on my remote server but am unable to activate the template for Limesurvey. Did I miss some steps?

**Comment by mofog** [comment]
Hey there, I'm sorry for the late response! If it is still of concern, make sure you extracted the ZIP to {DOCUMENT_ROOT}/upload/templates/BootstrapForLimeSurvey (so the contents of that directory should contain two sub-directories and all the files, e.g., template.js). The template should then show up in the list in the backend. Note that this template only supports LimeSurvey 2.06 and not 2.50.
