### ISSUE TITLE
Can't find a manifest for mofog-BootstrapForLimeSurvey-fcb002a

### ISSUE THREAD

**Issue by ln-12** [mofog/BootstrapForLimeSurvey#25]
Hey, I tried to install your template, but got the following error:
```
Error: Can't find a manifest for mofog-BootstrapForLimeSurvey-fcb002a in ' /app/themes/survey/mofog-BootstrapForLimeSurvey-fcb002a/ '
```
Do you know how to fix it?

**Comment by mofog** [comment]
Hello,

based on the provided error message, I assume you're using LimeSurvey 3.x. However, the template is only available for LimeSurvey 2.06+, as indicated in the readme – sorry.
